//! Phase 31 PR 2: measures whether `search_two_step_routes`
//! (`src/multi_step.rs`, unchanged since PR 1) can recover real,
//! literature-cited targets that gugen's existing single-step search
//! structurally cannot reach, when fed corpus-grounded candidate
//! intermediates instead of hand-supplied synthetic ones.
//!
//! **Data, not fabrication.** The holdout
//! (`benchmarks/data/kononova_high_arity_sample.jsonl`, generated by
//! `benchmarks/fetch_kononova_high_arity.py`) is every real Kononova et
//! al. 2019 reaction needing more than `SearchBudget::default()
//! .max_precursors_per_plan` (4) distinct precursors -- exactly the
//! reactions `fetch_kononova.py`'s own committed sample discards. The
//! intermediate-candidate pool is a single global `FrequencyPriorGenerator`
//! (already shipped, Phase 30 PR 1, unchanged) built from every precursor
//! formula in the already-committed, disjoint `kononova_sample.jsonl` --
//! no new hand-written decomposition rule, no fabricated "known route".
//!
//! **What this does and does not claim** (see also
//! `docs/phase31_pr2_two_step_arity_recall.md`): this measures gugen's
//! own two-step *search capability* against real high-arity targets. It
//! is NOT a claim that the intermediate composition found matches any
//! documented real synthesis procedure -- no per-step ground truth
//! exists in any corpus available to this project to check that against
//! (see this phase's own doc for the tier-1/tier-2/tier-3 research that
//! established this).
//!
//! Run: `cargo run --release --example exploration_two_step_arity_recall --features serde`
//! (after `python3 benchmarks/fetch_kononova_high_arity.py`, already run
//! and committed as of this PR).
//!
//! Writes `benchmarks/data/exploration_two_step_arity_recall_result.json`.

use gugen::{
    CandidateGenerator, Composition, Element, FrequencyPriorGenerator, PlanningConstraints,
    PrecursorCandidate, PrecursorId, SearchBudget, search_two_step_routes,
};
use std::collections::BTreeMap;

const LOW_ARITY_JSONL: &str = include_str!("../benchmarks/data/kononova_sample.jsonl");
const HIGH_ARITY_JSONL: &str = include_str!("../benchmarks/data/kononova_high_arity_sample.jsonl");
const OUTPUT_PATH: &str = "benchmarks/data/exploration_two_step_arity_recall_result.json";

/// How many top-frequency candidate intermediates are tried per holdout
/// row -- bounds `search_two_step_routes`'s own "1 + N + 1" search-call
/// cost per row (`src/multi_step.rs`'s own doc comment). Calibrated
/// empirically, not guessed: swept 20/50/100/200/380 and net-new
/// two-step recall rose monotonically at every step (0/1/5/9/12 out of
/// 294), never saturating below the frequency table's own full size
/// (380 distinct precursor formulas in `kononova_sample.jsonl`) -- so
/// capping below the table's actual size only threw away real signal
/// for no cost benefit (each row's search pool stays tiny regardless;
/// the full run still completes in seconds). Set generously above the
/// table's current size rather than removing the cap outright, so a
/// much larger future frequency table doesn't silently make a single
/// row's search unbounded.
const MAX_INTERMEDIATE_CANDIDATES: usize = 2_000;

#[derive(serde::Deserialize)]
struct CorpusPrecursor {
    formula: String,
    elements: BTreeMap<String, f64>,
}

#[derive(serde::Deserialize)]
struct CorpusRow {
    doi: Option<String>,
    target_formula: Option<String>,
    target_elements: BTreeMap<String, f64>,
    precursors: Vec<CorpusPrecursor>,
}

fn load_jsonl(raw: &str, source_hint: &str) -> Vec<CorpusRow> {
    raw.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| {
            serde_json::from_str(l)
                .unwrap_or_else(|e| panic!("{source_hint} must be valid JSONL: {e}"))
        })
        .collect()
}

/// Defensively re-validated against gugen's own types, matching
/// `examples/large_scale_benchmark.rs`'s identical precedent -- a large
/// real external corpus can always contain an edge case neither side's
/// filter anticipated.
fn try_composition(elements: &BTreeMap<String, f64>) -> Option<Composition> {
    let pairs: Option<Vec<(Element, f64)>> = elements
        .iter()
        .map(|(sym, amt)| Element::new(sym).ok().map(|e| (e, *amt)))
        .collect();
    Composition::new(pairs?).ok()
}

struct ParsedRow {
    doi: String,
    target_formula: String,
    target: Composition,
    precursors: Vec<PrecursorCandidate>,
}

fn parse_rows(raw: Vec<CorpusRow>) -> (Vec<ParsedRow>, usize) {
    let mut parsed = Vec::with_capacity(raw.len());
    let mut unparseable = 0;
    for row in raw {
        let Some(target) = try_composition(&row.target_elements) else {
            unparseable += 1;
            continue;
        };
        let mut precursors = Vec::new();
        let mut ok = true;
        for p in &row.precursors {
            let Some(composition) = try_composition(&p.elements) else {
                ok = false;
                break;
            };
            precursors.push(PrecursorCandidate {
                id: PrecursorId(p.formula.clone()),
                composition,
                availability: None,
            });
        }
        if !ok || precursors.is_empty() {
            unparseable += 1;
            continue;
        }
        parsed.push(ParsedRow {
            doi: row.doi.unwrap_or_default(),
            target_formula: row.target_formula.unwrap_or_default(),
            target,
            precursors,
        });
    }
    (parsed, unparseable)
}

/// One global "how often is this a real cited precursor" table, built
/// once from every low-arity row's own precursor list (the disjoint,
/// already-committed `kononova_sample.jsonl` -- never from the
/// high-arity holdout itself, which would leak each row's own answer
/// into its own candidate pool). First-seen composition per formula,
/// matching `examples/large_scale_benchmark.rs`'s `decoy_pool` precedent.
fn build_frequency_table(rows: &[ParsedRow]) -> Vec<(PrecursorCandidate, u64)> {
    let mut counts: BTreeMap<String, (u64, Composition)> = BTreeMap::new();
    for row in rows {
        for p in &row.precursors {
            counts
                .entry(p.id.0.clone())
                .and_modify(|(n, _)| *n += 1)
                .or_insert((1, p.composition.clone()));
        }
    }
    counts
        .into_iter()
        .map(|(formula, (count, composition))| {
            (
                PrecursorCandidate {
                    id: PrecursorId(formula),
                    composition,
                    availability: None,
                },
                count,
            )
        })
        .collect()
}

/// Real, corpus-grounded candidates for `target`, filtered to
/// compositions structurally simpler than the target itself (fewer
/// distinct elements -- an intermediate that isn't simpler than the
/// target it's meant to help reach isn't a useful stepping stone) and
/// not already present in `base_candidates` (an intermediate identical
/// to an existing precursor adds nothing `search_two_step_routes`'s own
/// direct-search pass hasn't already tried). Capped to the
/// `MAX_INTERMEDIATE_CANDIDATES` highest-frequency survivors.
fn intermediate_candidates_for(
    generator: &FrequencyPriorGenerator,
    target: &Composition,
    base_candidates: &[PrecursorCandidate],
) -> Vec<Composition> {
    let target_arity = target.iter().count();
    let base_compositions: Vec<&Composition> =
        base_candidates.iter().map(|c| &c.composition).collect();
    generator
        .generate(target, &PlanningConstraints::default())
        .expect("frequency-prior generation must not fail on a well-formed target")
        .into_iter()
        .map(|gc| gc.candidate.composition)
        .filter(|c| c.iter().count() < target_arity)
        .filter(|c| !base_compositions.contains(&c))
        .take(MAX_INTERMEDIATE_CANDIDATES)
        .collect()
}

fn main() {
    let low_arity = parse_rows(load_jsonl(LOW_ARITY_JSONL, "kononova_sample.jsonl")).0;
    let (holdout, holdout_unparseable) = parse_rows(load_jsonl(
        HIGH_ARITY_JSONL,
        "kononova_high_arity_sample.jsonl",
    ));

    let frequency_table = build_frequency_table(&low_arity);
    let frequency_table_size = frequency_table.len();
    let generator = FrequencyPriorGenerator::new(frequency_table);
    let budget = SearchBudget::default();

    let mut recovered_two_step = 0usize;
    let mut recovered_one_step = 0usize;
    let mut recovered_two_step_net_new = 0usize; // two_step_hit && !one_step_hit
    let mut search_errors: Vec<String> = Vec::new();
    let mut by_arity: BTreeMap<usize, (usize, usize)> = BTreeMap::new(); // arity -> (total, recovered)
    let mut rows_out: Vec<String> = Vec::with_capacity(holdout.len());

    for row in &holdout {
        let arity = row.precursors.len();
        let intermediates = intermediate_candidates_for(&generator, &row.target, &row.precursors);

        // A discovered, pre-existing defect (unrelated to this PR's own
        // code -- see docs/phase31_pr2_two_step_arity_recall.md's
        // Discovered Work section) can make `search_precursor_sets`
        // return a spurious "accepted" identity reaction (a precursor
        // whose composition exactly equals one of `curated_byproducts()`,
        // e.g. elemental O2, balances trivially against itself). Coupled
        // with `search_two_step_routes`'s own `?`-per-entry loop, one such
        // spurious entry aborts route construction for the *entire* row,
        // not just that one entry. Rather than patching either function
        // (out of scope for this measurement-only PR -- both are
        // pre-existing, unrelated to two-step orchestration itself, and
        // deserve a dedicated fix+regression pass), affected rows are
        // excluded here and reported by name, not silently dropped.
        let routes = match search_two_step_routes(
            &row.target,
            &row.precursors,
            &intermediates,
            &PlanningConstraints::default(),
            &budget,
        ) {
            Ok(routes) => routes,
            Err(e) => {
                search_errors.push(format!(
                    "    {{\"doi\": {:?}, \"target_formula\": {:?}, \"error\": {:?}}}",
                    row.doi,
                    row.target_formula,
                    e.to_string()
                ));
                continue;
            }
        };

        let two_step_hit = routes.iter().any(|r| {
            r.stages().len() >= 2
                && r.final_reaction()
                    .products()
                    .iter()
                    .any(|s| s.composition == row.target)
        });
        let one_step_hit = routes.iter().any(|r| {
            r.stages().len() == 1
                && r.final_reaction()
                    .products()
                    .iter()
                    .any(|s| s.composition == row.target)
        });

        if two_step_hit {
            recovered_two_step += 1;
        }
        if one_step_hit {
            recovered_one_step += 1;
        }
        if two_step_hit && !one_step_hit {
            recovered_two_step_net_new += 1;
        }

        // Only a row NOT already reachable in one step is a genuine test
        // of two-step search's own contribution -- a row reachable in one
        // step didn't need two-step help, regardless of arity as *listed*
        // by the corpus (see module doc: many "high-arity" listed
        // precursor sets turn out to have a smaller reachable subset).
        if !one_step_hit {
            let entry = by_arity.entry(arity).or_insert((0, 0));
            entry.0 += 1;
            if two_step_hit {
                entry.1 += 1;
            }
        }

        rows_out.push(format!(
            "    {{\"doi\": {:?}, \"target_formula\": {:?}, \"arity\": {arity}, \
            \"intermediate_candidates_tried\": {}, \"two_step_recovered\": {two_step_hit}, \
            \"one_step_recovered\": {one_step_hit}}}",
            row.doi,
            row.target_formula,
            intermediates.len(),
        ));
    }

    let total = holdout.len();
    let evaluated = total - search_errors.len();
    let truly_unreachable_in_one_step = evaluated - recovered_one_step;
    println!("Phase 31 PR 2: two-step search recall against real high-arity literature targets");
    println!(
        "total holdout rows: {total} ({holdout_unparseable} unparseable, skipped; {} excluded \
        by a discovered pre-existing search defect, see module doc); \
        frequency table built from {} distinct precursor formulas across {} low-arity rows",
        search_errors.len(),
        frequency_table_size,
        low_arity.len()
    );
    println!(
        "already reachable in one step despite >4 *listed* precursors (a smaller real subset \
        sufficed -- see module doc): {recovered_one_step}/{evaluated}"
    );
    println!(
        "two-step search found a valid route (any) for: {recovered_two_step}/{evaluated}; of \
        those, net-new (target NOT already reachable in one step): \
        {recovered_two_step_net_new}/{truly_unreachable_in_one_step} genuinely-unreachable rows \
        = {:.4} (relative to the raw {total}-row holdout: {:.4})",
        recovered_two_step_net_new as f64 / truly_unreachable_in_one_step.max(1) as f64,
        recovered_two_step_net_new as f64 / total.max(1) as f64
    );
    if !search_errors.is_empty() {
        println!(
            "{} rows excluded by the discovered search defect (not counted above): see \
            \"search_errors\" in the result file",
            search_errors.len()
        );
    }
    println!("by arity (genuinely-unreachable-in-one-step rows only):");
    for (arity, (row_total, row_recovered)) in &by_arity {
        println!(
            "  arity {arity}: {row_recovered}/{row_total} = {:.4}",
            *row_recovered as f64 / *row_total.max(&1) as f64
        );
    }

    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(
        "  \"description\": \"Phase 31 PR 2 -- search_two_step_routes recall against real, \
        literature-cited targets whose corpus-listed precursor count exceeds \
        SearchBudget::default().max_precursors_per_plan, using a corpus-grounded \
        FrequencyPriorGenerator as the intermediate-candidate source. two_step_found_any_route \
        counts every row where a returned route (1- or 2-stage) matches the target; \
        two_step_recovered_net_new is the honest gate metric -- only rows where the target was \
        NOT already reachable in one step from a smaller real subset (see \
        one_step_recovered_despite_high_listed_arity). Not a claim that any recovered intermediate \
        matches a documented real synthesis procedure -- see this file's generating example's own \
        module doc. search_errors lists rows excluded by a discovered, pre-existing, unrelated \
        search defect (see module doc's Discovered Work note), not counted in any recall figure.\",\n",
    );
    out.push_str(&format!("  \"holdout_total\": {total},\n"));
    out.push_str(&format!(
        "  \"holdout_unparseable_skipped\": {holdout_unparseable},\n"
    ));
    out.push_str(&format!(
        "  \"excluded_by_discovered_search_defect\": {},\n",
        search_errors.len()
    ));
    out.push_str(&format!("  \"evaluated\": {evaluated},\n"));
    out.push_str(&format!(
        "  \"max_intermediate_candidates\": {MAX_INTERMEDIATE_CANDIDATES},\n"
    ));
    out.push_str(&format!(
        "  \"one_step_recovered_despite_high_listed_arity\": {recovered_one_step},\n"
    ));
    out.push_str(&format!(
        "  \"truly_unreachable_in_one_step\": {truly_unreachable_in_one_step},\n"
    ));
    out.push_str(&format!(
        "  \"two_step_found_any_route\": {recovered_two_step},\n"
    ));
    out.push_str(&format!(
        "  \"two_step_recovered_net_new\": {recovered_two_step_net_new},\n"
    ));
    out.push_str(&format!(
        "  \"two_step_recall_net_new_of_truly_unreachable\": {:.6},\n",
        recovered_two_step_net_new as f64 / truly_unreachable_in_one_step.max(1) as f64
    ));
    out.push_str(&format!(
        "  \"two_step_recall_net_new_of_raw_holdout\": {:.6},\n",
        recovered_two_step_net_new as f64 / total.max(1) as f64
    ));
    out.push_str("  \"by_arity_of_truly_unreachable\": {\n");
    let arity_entries: Vec<String> = by_arity
        .iter()
        .map(|(arity, (row_total, row_recovered))| {
            format!("    \"{arity}\": {{\"total\": {row_total}, \"recovered\": {row_recovered}}}")
        })
        .collect();
    out.push_str(&arity_entries.join(",\n"));
    out.push_str("\n  },\n");
    out.push_str("  \"search_errors\": [\n");
    out.push_str(&search_errors.join(",\n"));
    out.push_str("\n  ],\n");
    out.push_str("  \"rows\": [\n");
    out.push_str(&rows_out.join(",\n"));
    out.push_str("\n  ]\n");
    out.push_str("}\n");

    std::fs::write(OUTPUT_PATH, &out).expect("failed to write result");
    println!();
    println!("wrote {OUTPUT_PATH}");
}
